language: python
python:
- 3.6

sudo: false
addons:
  apt:
    packages:
    - python-pip

install:
- pip install xml2rfc
script:
- xml2rfc --text ./index.xml -o index.txt
- xml2rfc --html ./index.xml -o index.html

branches:
  only:
  - gh-pages
  - /.*/
